### ISSUE TITLE
As a user logging into a service requiring MFA, I want to be told clearly that I must use the eduID app every step

### ISSUE THREAD

**Issue by FlorisFokkinga** [OpenConext/OpenConext-myconext#165]
This screen is rather clear: 'to proceed to <service> you must <use eduID app>'

<img width="459" alt="image" src="https://github.com/OpenConext/OpenConext-myconext/assets/80269262/29ad9bec-e078-4111-8009-0cc4542f156b">

If the user chooses to ignore this warning or, perhaps, doesn't read all this text, the next screen is less clear.

<img width="498" alt="image" src="https://github.com/OpenConext/OpenConext-myconext/assets/80269262/c7f70e6e-be15-401d-9884-09845732be40">

'Login without the eduApp is strongly discouraged.' While it is impossble, like the previous screen said.
'The <service> will not receive your attributes'. Most people have no idea what this means. It means you cannot login to the service.

If the user continues anyway, the next screen is just wrong. It's not the user's institution that denies access.

<img width="755" alt="image" src="https://github.com/OpenConext/OpenConext-myconext/assets/80269262/0eb25f5c-0495-416d-8105-c12839dba40a">

To be clear: the problem is not that logging in doesn't work, but that after ignoring the first warning, the warnings and errors become less clear and accurate.

**Comment by thijskh** [comment]
Also the word "eduApp" just appears out of nowhere in the second screen.
