### ISSUE TITLE
Button 'Mijn eduID' isn't translated to English

### ISSUE THREAD

**Issue by FlorisFokkinga** [OpenConext/OpenConext-myconext#189]
https://eduid.nl/en/
![image](https://github.com/OpenConext/OpenConext-myconext/assets/80269262/fdbcfadd-7e30-4ee5-bde8-8cfb954b3ab8)

**Comment by phavekes** [comment]
The eduID.nl website is not a part of openconext-myconext. See https://github.com/SURFnet/eduid-wordpress-theme
