### ISSUE TITLE
Magic link in logging

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#48]
Is this the correct logging here? It seems to be in a magic-link handler, and I can't find a "successful login with magiclink" log line anywhere. Am I missing something?

https://github.com/OpenConext/OpenConext-myconext/blob/aefd90780ebd795cefe8c62d5c4164f2a36ecdaf/myconext-server/src/main/java/myconext/api/UserController.java#L191

**Comment by oharsta** [comment]
It is the correct login. The passwords match and the SAML assertion response is send  - after one more redirect - to the (proxy) SP. 

You are right that there is no "successful login with magiclink" log entry. However there is a log entry in https://github.com/OpenConext/OpenConext-myconext/blob/master/myconext-server/src/main/java/myconext/security/GuestIdpAuthenticationRequestFilter.java#L311 that indicates an user has used his / hers magic link successful.

I agree that this could be logged more explicit.

**Comment by phavekes** [comment]
Will be fixed by https://www.pivotaltracker.com/story/show/174972563
