### ISSUE TITLE
Update entering name when deleting

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#530]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/188191543)    

    When we\'ve added formal and self-chosen names, the \'Are you sure you want to delete your account\' dialog wasn;t updated, and still asks for a `full name`. 

Discussion: 
Is it needed to enter your name? Should it be the formal name, or the self-chosen name? Is Entering \'Delete\' also enough?

**Comment by phavekes** [comment]
In the use case where the user was verified and he delete this verification, the \'validated\' surname and given name are still \'visible\' even though they are no longer recognised as \'validated\'. However it might lead to a confusing situation for an end user, which name should she type to delete here account. 

Also think about the iDIN given name, which will be \'I\' in my case, not Ines. Which also might lead to confusion if I want to delete my account and type \'my name\'  (inesduits - Aug 29, 2024)

**Comment by phavekes** [comment]
Besloten 5 sept 2024: Typen \'Delete\' of \'Verwijder\' als bevestiging. (Peter Havekes - Sep 5, 2024)

**Comment by phavekes** [comment]
Related to https://www.pivotaltracker.com/story/show/187955753
 (Peter Havekes - Sep 5, 2024)

**Comment by Tyskai** [comment]
![Image](https://github.com/user-attachments/assets/94204101-4821-4bdb-914c-f37477ddb1e2)
It looks like there is "just" a big red delete button. It does not have the "type delete" field. Overlooked? @oharsta

**Comment by oharsta** [comment]
@Tyskai This is not the screen referenced in this story. It entails the Account section where you can delete your entire account (not just en eduID).
<img width="502" alt="image" src="https://github.com/user-attachments/assets/fb57d52f-6627-4f36-b901-ebf3f9aaaf16">

**Comment by Tyskai** [comment]
You are right, I am sorry!
