### ISSUE TITLE
New API endpoint for Invite

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#533]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/188249791)    

    Add new API endpoint to eduID for Invite user:

Input : any targeted existing eduID identifier + InstitutionGUID

eduID will lookup or create the eduID identifier for the institution, and return this

**Comment by oharsta** [comment]
Fixed in https://github.com/OpenConext/OpenConext-myconext/commit/f3c11deff960a415881e038d5db9da8bb06b4155
