### ISSUE TITLE
App nudge minder vaak tonen

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#535]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/188225417)    

Toon alleen de nudge naar de app als je meer dan 24 uur, maar minder dan x (configureerbaar) dagen geleden geleden hebt ingelogd. Dus niet bij het onboarden, maar alleen bij latere bezoeken.
Op deze manier wordt de nudge alleen getoond  aan gebruikers die vaak eduID gebruiken, en dus ook iets aan de app hebben.

**Comment by oharsta** [comment]
For now, the implementation is simple. We don't show the nudge-to-app the first 24 hours. And after that every X days, if the user uses the magic-link flow. If it needs to be more complex (and we need to keep track of the last login), then we revisit this story.

**Comment by phavekes** [comment]
De eerste 24 uur tonen we de nudge niet, en daarna alleen als < `nudge_eduid_app_login_days`  en nog geen geregistreerde app heeft.
Als de nudge getoond is, wordt deze `nudge_eduid_app_pause_days`
niet getoond
