### ISSUE TITLE
Always ask whether a user wants to use their 'new' name (also with iDIN and eIDAS)

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#541]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/188251720)    

When a user adds a second affiliation / school, he gets the question whether or not he wants to \'the following information\'.

However, when a user does iDIN/eIDAS, and then does add an organisation as step two, this question is not asked.

**Comment by phavekes** [comment]
This screen! (inesduits - Sep 10, 2024)

**Comment by oharsta** [comment]
Fixed in https://github.com/OpenConext/OpenConext-myconext/commit/c9ea200d557523536cf8c56c16021424e527a31f
