### ISSUE TITLE
Waarschuw gebruikers met een instellings-mail

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#545]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/188225554)    

Waarschuw gebruikers met een instellings email dat ze na het beeindigen van de studie geen toegang meer hebben, en ze te motiveren een naar een privee mailadres te verhuizen.

Time interval should be configurable.
Default times: 1 February, 1 June, 1 October.

E-mail template, should be in 2 languages. 
Placeholder text:
"Hoi {roepnaam},
Je hebt een eduID aangemaakt met je instelling account. Als je je instellingsaccount gebruikt, en je bent bijvoorbeeld klaar met je opleiding verlies je de toegang tot je eduID. Dit terwijl je je eduID ook na je opleiding weer kan gebruiken. Daarom raden we je aan om gewoon je eigen e-mail te gebruiken. Je kunt in je instellingen van je eduID account je e-mail adres wijzigen.
Vriendelijke groetjes,
eduID.
"

**Comment by phavekes** [comment]
This will cause 9000+ emails on 1st run

**Comment by Tyskai** [comment]
Release today to production in dry run, meaning: no real mails are sent yet in production (or acceptation).
