### ISSUE TITLE
Stuur mail voor app-nudge

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#547]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/188225431)    

Wijs een gebruiker X dagen  na het aanmaken van zijn account op de mogelijkheid een app te gebruiken. Deze triggered voor gebruikers die de app nog niet hebben: "name: "eduID mobile app""

Email temple should be in 2 languages. Nudge interval should configurable. Nudge should be sent: {2 week after account creation}.

Email template/placeholder:
"Hoi {roepnaam},
Je hebt een eduID account aangemaakt maar de app niet geïnstalleerd. Het is super veel handiger als je de app wel installeert, daarmee kan je sneller inloggen. Ga naar eduid.nl om je account aan je eduID app te koppelen. 
Groetjes,
eduID
"

**Comment by phavekes** [comment]
@MarliesRikken Kun jij hiervoor de tekst (nl+en) aanleveren?

**Comment by MarliesRikken** [comment]
Voorstel:

--- NL ---
Onderwerp: Verhoog de beveiliging van je eduID met de eduID app

Beste [Naam],

Welkom bij eduID! Om jouw eduID-account nog beter te beveiligen en het inloggen makkelijker te maken, raden we je aan de eduID app te installeren.

Met de app kun je:

    Veiliger en sneller inloggen.
    Je account beter beschermen met extra beveiligingsopties.

Download de app via [link naar de app] en maak je eduID ervaring nóg eenvoudiger.

Heb je vragen? We helpen je graag! (link to: help@eduid.nl )

Met vriendelijke groet,
Het eduID-team

--- EN ---
Subject: Improve your eduID security with the eduID App

Dear [Name],

Welcome to eduID! To better secure your eduID account and make logging in easier, we recommend installing the eduID app.

With the app, you can:

    Log in faster and more securely.
    Protect your account with additional security options.

Download the app here: [link to the app] and simplify your eduID experience.

If you have any questions, feel free to reach out! (link to: help@eduid.nl )

Kind regards,
The eduID Team

**Comment by Tyskai** [comment]
Release today to production in dry run, meaning: no real mails are sent yet in production (or acceptation). Next to that all users who already have an account for some time have their "nudgeAppMailSend" on true (Even though they did not receive the mail).
