### ISSUE TITLE
Recognise when users did not complete the registration process

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#602]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/172048954)    

Some users fail to complete the registration process (becuase they forget to click the link in the confirmation email). When they later return to eduID, they want to register again. But then, they get an error that their email address is already used for eduID. This is confusing.

It would be nice if eduID recognises that the user was already trying to register but that the registration process was not yet finished. And when re-initialising the registration process, the user should be taken back to where it went wrong in the 1st place, so that it can be completed again.

**Comment by Tyskai** [comment]
Not breaking and old issue, which is mostly fixed.
If user aborts the registration process the user can either wait a bit, for our automatic "remove accounts that not completed the registration process" to be finished. Or they register again, get a nudge that they already have an account, and try to login, which will work!
