### ISSUE TITLE
Mobile API ServiceProvider.createdAt is specified as String

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#616]
Mobile API ServiceProvider.createdAt is specified as String, but returns a unix timestamp. All other `createdAt` fields are specified as int64 (unix timestamp). This causes issues in the mobile app. Change the OpenAPI spec to match the content and other `createdAt` fields.

`Token.createdAt` is also specified as String. Should this be int64 to?

![image](https://github.com/user-attachments/assets/3fc96697-6e10-4b84-800c-c12524e7fcd3)

![image](https://github.com/user-attachments/assets/0f46d472-ea77-4cd3-b39c-9a5b4d402c09)

**Comment by dzolnai** [comment]
`Token.createdAt` did not change recently, we already use it as a string in the app, so that should be fine.
