### ISSUE TITLE
eppn and subjectID for linked accounts

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#628]
For linked accounts, a user can only have a subjectID (eg Leidenuniv). 
SubjectID is more reliable than eppn, so we should prefer this.

- A linked account should have an eppn, or subjectID. 
- If both are present, the subjectId is prefered
- When adding a linked account, also validate the uniqueness of the subjectId

**Comment by phavekes** [comment]
5 gebruikers hebben wel een linked account, maar geen subjectId of eppn:
`db.users.find({ "linkedAccounts.schacHomeOrganization": { $exists: true, $ne: null, $ne: "" }, "linkedAccounts.eduPersonPrincipalName": { $exists: false }, "linkedAccounts.subjectId": { $exists: false } }).count();`

**Comment by phavekes** [comment]
Om deze accounts te ont-linken:
```
db.users.updateMany(
    {
        "linkedAccounts.schacHomeOrganization": { $exists: true, $ne: null, $ne: "" },
        "linkedAccounts.eduPersonPrincipalName": { $exists: false },
        "linkedAccounts.subjectId": { $exists: false }
    },
    {
        $set: { "linkedAccounts": {} }  // Maak het linkedAccounts object leeg
    }
)
```

**Comment by Tyskai** [comment]
Updated the test database! 2 users affected. Did not do acc or prod (yet)!
