### ISSUE TITLE
Remove references to eherkenning

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-myconext#640]
Al thou the provider may use the word eherkenning in the service, this is actually eIDAS. Rename all occurences of eherkenning to eIDAS, also in url's.

![Image](https://github.com/user-attachments/assets/a979001d-ba98-4315-8993-45bf239d7c63)
![Image](https://github.com/user-attachments/assets/99b10d5c-b820-4852-bb5b-dbe1eb06bfa1)

**Comment by oharsta** [comment]
@phavekes , @Tyskai 

Proposal:

We will change all references in the UI, but we'll keep the references in the code and in the database. The eherkenning term is used as the name of the issuer in the response from the API, we want to adhere to the original name. I also strongly recommend not to change the term in URL's as this a 1-to-1 copy of the issuer name. 

To discuss.

**Comment by Tyskai** [comment]
@oharsta ( and @phavekes ) Your proposal sounds good to me! Technically we get "eherkenning" back and such, but if the user only sees eIDAS that is perfect! 

![Image](https://github.com/user-attachments/assets/36f9a7b0-5fac-4819-95b4-666bd39de9f4)

**Comment by phavekes** [comment]
We should also update/rewrite the refrences in de (mobile) api, at least where is't used as a `name`
