### ISSUE TITLE
idp metadata has wrong sso location

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-myconext#67]
The metadata (as found on https://login.eduid.nl/saml/guest-idp/metadata) has 

```xml
<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://login.eduid.nl/saml/guest-idp/SSO/alias/guest-idp"/>
<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://login.eduid.nl/saml/guest-idp/SSO/alias/guest-idp"/>
```

while it turns out that it only works when you leave out the last `/alias/guest-idp` of those URLs.

**Comment by oharsta** [comment]
Seems to be buried deep in the SAML library we use: https://github.com/spring-projects/spring-security-saml/blob/develop/core/src/main/java/org/springframework/security/saml/provider/provisioning/AbstractHostbasedSamlProviderProvisioning.java#L97. 

Also see https://www.pivotaltracker.com/story/show/175373291 - EOL of spring-security-saml

**Comment by thijskh** [comment]
Nothing that Apache [mod_sed](https://httpd.apache.org/docs/trunk/mod/mod_sed.html) can't solve 😄

**Comment by oharsta** [comment]
Solved by using new SAML library: https://login.test2.eduid.nl/saml/guest-idp/metadata/
