### ISSUE TITLE
'Connect new organisation' fails when myConext is not hooked up to OpenConext (govroam)

### ISSUE THREAD

**Issue by govroam** [OpenConext/OpenConext-myconext#69]
In the govroam deployment, myConext is not connected to an OpenConext instance. 
When a user goes to 'My govID' > 'Connect new organisation', and choses 'proceed', the link can (of course) not be followed.

Could it be an option to hide the menu item 'Connections'?

**Comment by oharsta** [comment]
Implemented in https://github.com/OpenConext/OpenConext-myconext/commit/45a556b84f9b8c26a70a559949db258344938ab1. The toggle is here: https://github.com/OpenConext/OpenConext-myconext/blob/master/myconext-server/src/main/resources/application.yml#L47
